### ISSUE TITLE
[PE-D][Tester B] Tokenizers are case sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-1/tp#101]
![image.png](https://raw.githubusercontent.com/ShummyOwnzYou/ped/main/files/6987f590-981e-45d4-b119-5c006f4a848c.png)

tokenizers are case sensitive, but UG does not state this functionality.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ShummyOwnzYou/ped#2

**Comment by guowei42** [comment]
State in UG

**Comment by guowei42** [comment]
resolved #148
