### ISSUE TITLE
[PE-D][Tester C] Traces of Addressbook still exists

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-1/tp#105]
![image.png](https://raw.githubusercontent.com/gerardstevan/ped/main/files/43fe2512-01bd-41f8-97fd-ba59666c8341.png)

![image.png](https://raw.githubusercontent.com/gerardstevan/ped/main/files/60209278-5ce9-470e-a4a3-68690425d919.png)

There are still traces of the old Addressbook visible in your app, such as the jar file name and the json file name shown in the app 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gerardstevan/ped#4

**Comment by guowei42** [comment]
Change naming

**Comment by guowei42** [comment]
`\data\addressbook.json` should be in `UserPref` class
