### ISSUE TITLE
[PE-D][Tester B] Grade does not reset when assignments are overwritten

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-1/tp#114]
![image.png](https://raw.githubusercontent.com/ShummyOwnzYou/ped/main/files/6f9fdf6c-3200-4575-97f9-b55c9d8aa90a.png)

Grade does not reset when assignments are overwritten

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ShummyOwnzYou/ped#5

**Comment by yellow-294** [comment]
Student#SetAssignments to reset overallGrade

**Comment by KJunWei** [comment]
resolved, thank you!
