### ISSUE TITLE
[PE-D][Tester D] Error in graph after using the `assignments` command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-1/tp#133]
When i give the command,

`assignments assignments/ Assignment 1 w/15, Assignment 2 w/15, Midterms w/30, Finals w/40`

I am unable to see `Assignment 2` written on the x-axis of the graph, when the window width is less.

![image.png](https://raw.githubusercontent.com/pratham31012002/ped/main/files/be0139e6-43bb-471d-851d-e2c6439bacde.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: pratham31012002/ped#8

**Comment by yellow-294** [comment]
Specify in UG the constraints and to extend window if too many assignments
