### ISSUE TITLE
[PE-D][Tester A] Duplicate email are allowed but in a school setting email should be unique.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-1/tp#137]
![image.png](https://raw.githubusercontent.com/Kang-Quan/ped/main/files/5b9dd7ce-f40a-453f-ad1f-e11067e31f13.png)

![image.png](https://raw.githubusercontent.com/Kang-Quan/ped/main/files/89b89d03-050d-437f-949d-0093b02c8074.png)

Similar issue found with phone number.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Kang-Quan/ped#5

**Comment by guowei42** [comment]
change equal method to phone and email, similar to name. Plus add error message.
