### ISSUE TITLE
[PE-D][Tester C] Un-updated invalid command message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-1/tp#99]
![image.png](https://raw.githubusercontent.com/gerardstevan/ped/main/files/401d580f-b219-4126-ae0e-c0873a2e31df.png)
 
The app still have address book in it when entering invalid add command

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: gerardstevan/ped#1

**Comment by guowei42** [comment]
Change "address book" to TAB.
